<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Include="index.html" />
    <Compile Include="CounterLogic.fs" />
    <Compile Include="CounterView1.fs" />
    <Compile Include="CounterView2.fs" />
    <Compile Include="Program.fs" />
    <TypeScriptCompile Include="vite.config.mts" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Elmish" />
    <PackageReference Include="Fable.Elmish.React" />
    <PackageReference Include="Fable.React" />
    <PackageReference Include="Feliz" />
  </ItemGroup>
</Project>
