<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Include="index.html" />
    <Compile Include="WeatherForecast.fs" />
    <Compile Include="Client.fs" />
    <TypeScriptCompile Include="vite.config.mts" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Browser.DOM" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Fetch" />
    <PackageReference Include="Thoth.Json" />
  </ItemGroup>
</Project>
