<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <DefineConstants>FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Include="index.html" />
    <Compile Include="WeatherForecast.fs" />
    <Compile Include="Client.fs" />
    <TypeScriptCompile Include="vite.config.mts" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Browser.DOM" Version="2.18.1" />
    <PackageReference Include="Fable.Core" Version="4.5.0" />
    <PackageReference Include="Fable.Fetch" Version="2.7.0" />
    <PackageReference Include="Thoth.Json" Version="10.4.1" />
  </ItemGroup>
</Project>
