<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Include="IfThenElse.fsx" />
    <None Include="BasicsWithConstantsPatternMatching.fsx" />
    <None Include="TuplesPatternMatching.fsx" />
    <None Include="RecordsPatternMatching.fsx" />
    <None Include="TypesPatternMatching.fsx" />
    <None Include="Guards.fsx" />
  </ItemGroup>

</Project>
